name: CI Build Check
on:
  push:
  pull_request:
  workflow_dispatch:

env:
  GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
  CSE_API_KEY: ${{ secrets.CSE_API_KEY }}
  CSE_CX_ID: ${{ secrets.CSE_CX_ID }}
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  R2_BUCKET_NAME: ${{ secrets.R2_BUCKET_NAME }}
  R2_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
  R2_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
  R2_ENDPOINT: ${{ secrets.R2_ENDPOINT }}
  R2_PUBLIC_URL: ${{ secrets.R2_PUBLIC_URL }}
  UPSTASH_REDIS_URI: ${{ secrets.UPSTASH_REDIS_URI }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Bun Runtime
        uses: antongolub/action-setup-bun@v1
      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install dependencies
        run: bun i
      - name: Build project
        run: bun run build
