name: Deploy to Cloudflare Workers
on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  CI: true
  CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
  CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
  GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
  CSE_API_KEY: ${{ secrets.CSE_API_KEY }}
  CSE_CX_ID: ${{ secrets.CSE_CX_ID }}
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  R2_BUCKET_NAME: ${{ secrets.R2_BUCKET_NAME }}
  R2_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
  R2_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
  R2_ENDPOINT: ${{ secrets.R2_ENDPOINT }}
  R2_PUBLIC_URL: ${{ secrets.R2_PUBLIC_URL }}

jobs:
  version:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: checkout code repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Bun Runtime
        uses: antongolub/action-setup-bun@v1
      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "bun"
      - name: Install dependencies
        run: bun i
      - name: Build project
        run: bun build

      - name: Create .env file
        run: |
          echo "GROQ_API_KEY=${{ secrets.GROQ_API_KEY }}" > .env
          echo "CSE_API_KEY=${{ secrets.CSE_API_KEY }}" >> .env
          echo "CSE_CX_ID=${{ secrets.CSE_CX_ID }}" >> .env
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
          echo "R2_BUCKET_NAME=${{ secrets.R2_BUCKET_NAME }}" >> .env
          echo "R2_ACCESS_KEY_ID=${{ secrets.R2_ACCESS_KEY_ID }}" >> .env
          echo "R2_SECRET_ACCESS_KEY=${{ secrets.R2_SECRET_ACCESS_KEY }}" >> .env
          echo "R2_ENDPOINT=${{ secrets.R2_ENDPOINT }}" >> .env
          echo "R2_PUBLIC_URL=${{ secrets.R2_PUBLIC_URL }}" >> .env

      - name: Deploy to CF Workers
        run: |
          bun run deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
